Updating flatbuffer library version.
The file nano/ipc_flatbuffers_lib/generated/flatbuffers/nanoapi_generated.h will need to be regenerated by deleting the file and rebuilding.

An error like: error: no matching function for call to ‘nanoapi::Envelope::VerifyField<uint8_t> indicates the file has not been regenerated.

Adding -DNOGDI flag for WIN32 to prevent the ERROR macro within wingdi.h from colliding with ProtoIdGapAction::ERROR