Fix missing return on non-void function
Old implementation fails when building with [-Werror=return-type]:
/workspace/nano/node/bandwidth_limiter.cpp:44:1: error: control reaches
end of non-void function [-Werror=return-type]