Fix/add missing lib to nano_rpc build
Fixes build error:

CMakeFiles/nano_rpc.dir/entry.cpp.o: in function `(anonymous
namespace)::endpoint_hash_raw(boost::asio::ip::basic_endpoint<boost::asio::ip::udp>
const&)':
/workspace/nano/node/common.hpp:31: undefined reference to
`nano::ip_address_hash_raw(boost::asio::ip::address const&, unsigned
short)'
/usr/bin/ld: CMakeFiles/nano_rpc.dir/entry.cpp.o: in function
`(anonymous
namespace)::endpoint_hash_raw(boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>
const&)':
/workspace/nano/node/common.hpp:36: undefined reference to
`nano::ip_address_hash_raw(boost::asio::ip::address const&, unsigned
short)'