Update minimum OSX deployment target to 13.3 which is required by the OSX 14.4 SDK.
Fixes error:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:66:32: error: 'to_chars' is unavailable: introduced in macOS 13.3